site_name: Kelon Docs
theme: material

repo_name: foundato/kelon
repo_url: https://github.com/foundato/kelon

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

pages:
  - "Core Docs":
    - "Introduction": "index.md"
    - "Overview":
      - "Example": "core/overview/Simple-Example.md"
      - "Create Policies": "core/overview/example/Create-Policies.md"
      - "Configure Kelon": "core/overview/example/Configure-Kelon.md"
      - "Run the example": "core/overview/example/Run-Example.md"
    - "Philosophy":
      - "Why external Policy Enforcement": "core/philosophy/Why-External-Policy-Enforcement.md"
      - "What is a Policy": "core/philosophy/What-Is-A-Policy.md"
    - "Architecture":
      - "Components": "core/architecture/Components.md"
      - "Policy Translation": "core/architecture/Policy-Translation.md"
      - "Query-AST": "core/architecture/Query-AST.md"
    - "Integrating Kelon":
      - "Services and Kelon": "core/integration/Services-And-Kelon.md"
    - "Extending Kelon":
      - "Writing plugins": "core/extend/Write-Plugins.md"
      - "Writing call-operand-mappings": "core/extend/Write-Call-Operand-Mappings.md"
      - "Write a datasource plugin": "core/extend/Write-Datastore-Plugin.md"
  - "Operations":
    - "APIs": "operations/APIs.md"
    - "Configuration": "operations/Configuration.md"
    - "Deployment": "operations/Deployment.md"
    - "Monitoring": "operations/Monitoring.md"
    - "Security": "operations/Security.md"
    - "Testing": "operations/Testing.md"